<button data-target="#html-body" class="back-to-top action-secondary" title="<?= __('Back to top') ?>"
    <?php /* data-mage-init='{"Magento_Theme/js/scroll-to": { "attr": "data-target", "offset": "0" }}' */?>>
</button>
<script type="text/x-magento-init">
    {
        ".back-to-top": {
            "Magento_Theme/js/scroll-to": {
                "attr": "data-target",
                "offset": 0
            }
        }
    }
</script>
