<div class="promo-bar">
    <div class="top-container">
        Place here element to be pinned on up-scroll (nav icon, text, baner, etc.)
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".promo-bar": {
            "Magento_Theme/js/pinned-on-scroll": {
                "enabled": true,
                "pinnedClass": "is-pinned",
                "unpinnedClass": "is-unpinned"
            }
        }
    }
</script>
