<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-bind="scope: 'messages'">
    <!-- ko if: cookieMessages && cookieMessages.length > 0 -->
    <div role="alert" data-bind="foreach: { data: cookieMessages, as: 'message' }" class="messages">
        <div data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }">
            <div data-bind="html: $parent.prepareMessageForHtml(message.text)"></div>
        </div>
    </div>
    <!-- /ko -->

    <!-- ko if: messages().messages && messages().messages.length > 0 -->
    <div role="alert" data-bind="foreach: { data: messages().messages, as: 'message' }" class="messages">
        <div data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }">
            <div data-bind="html: $parent.prepareMessageForHtml(message.text)"></div>
        </div>
    </div>
    <!-- /ko -->
</div>
<?php
$routeName = $this->getRequest()->getRouteName() ;
$controllerName = $this->getRequest()->getControllerName();
$actionName = $this->getRequest()->getActionName();

if(($routeName == 'cms') ||
    ($routeName == 'catalog' && $controllerName == 'product' && $actionName == 'view') ||
    ($routeName == 'catalog' && $controllerName == 'category' && $actionName == 'view') ||
    ($routeName == 'catalogsearch' && $controllerName == 'result' && $actionName == 'index')) {
    $init = "init-faster";
} else {
    $init = "init";
}
?>
<script type="text/x-magento-<?= $init?>">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "messages": {
                            "component": "Magento_Theme/js/view/messages"
                        }
                    }
                }
            }
    }
</script>
